# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='family',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mysite.Family'),
        ),
    ]
