# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_person_dob'),
        ('mysite', '0002_auto_20171126_0018'),
    ]

    operations = [
    ]
