# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_merge_20171126_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Family'),
        ),
    ]
