# Generated by Django 2.0.13 on 2019-11-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20171126_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='last_known_location',
            field=models.CharField(default='', max_length=15000),
        ),
    ]
